// The August 2024 CDSCO tranche: 156 FDCs prohibited under section 26A of
// the Drugs and Cosmetics Act, 1940, S.O.3285(E) through S.O.3440(E), dated
// 12.08.2024. Transcribed verbatim from the MoHFW gazette notification.
// This tranche only — earlier (2016, 2018) and later (2025) are not included.
export interface BannedFdcRow {
  sn: number;
  rawText: string;
  notificationRef: string;
  notificationDate: string; // ISO date
}

const SOURCE_URL =
  "https://cdsco.gov.in/opencms/opencms/system/modules/CDSCO.WEB/elements/download_file_division.jsp?num_id=MTE4NzE=";

export const BANNED_FDC_SOURCE_URL = SOURCE_URL;

export const BANNED_FDC_2024: BannedFdcRow[] = [
  { sn: 1, rawText: "Amylase + Protease + Glucoamylase + Pectinase + Alpha Galactosidase + Lactase + Beta-Gluconase + Cellulase + Lipase + Bromelain + Xylanase + Hemicellulase + Malt diastase + Invertase + Papain", notificationRef: "S.O.3285(E)", notificationDate: "2024-08-12" },
  { sn: 2, rawText: "Antimony Potassium Tartrate + Dried Ferrous Sulphate", notificationRef: "S.O.3286(E)", notificationDate: "2024-08-12" },
  { sn: 3, rawText: "Benfotiamine + Silymarin + L-Ornithine L-aspartate + Sodium Selenite + Folic acid + Pyridoxine hydrochloride", notificationRef: "S.O.3287(E)", notificationDate: "2024-08-12" },
  { sn: 4, rawText: "Bismuth Ammonium Citrate + Papain", notificationRef: "S.O.3288(E)", notificationDate: "2024-08-12" },
  { sn: 5, rawText: "Cyproheptadine HCl + Thiamine HCl + Riboflavine + Pyridoxine HCl + Niacinamide", notificationRef: "S.O.3289(E)", notificationDate: "2024-08-12" },
  { sn: 6, rawText: "Cyproheptadine Hydrochloride + Tricholine Citrate + Thiamine Hydrochloride + Riboflavine + Pyridoxine Hydrochloride", notificationRef: "S.O.3290(E)", notificationDate: "2024-08-12" },
  { sn: 7, rawText: "Rabeprazole Sodium (As enteric coated tablet) + Clidinium Bromide + Dicyclomine HCl + Chlordiazepoxide", notificationRef: "S.O.3291(E)", notificationDate: "2024-08-12" },
  { sn: 8, rawText: "Fungal Diastase + Papain + Nux vomica Tincture + Cardamom Tincture + Casein Hydrolysed + Alcohol", notificationRef: "S.O.3292(E)", notificationDate: "2024-08-12" },
  { sn: 9, rawText: "Mefenamic Acid + Paracetamol Injection", notificationRef: "S.O.3293(E)", notificationDate: "2024-08-12" },
  { sn: 10, rawText: "Omeprazole Magnesium + Dicyclomine HCl", notificationRef: "S.O.3294(E)", notificationDate: "2024-08-12" },
  { sn: 11, rawText: "S-adenosyl methionine + Metadoxine + Ursodeoxycholic acid BP + L-Methylfolate Calcium eq. to L-Methylfolate + Choline bitartrate + Silymarin + L-ornithine L-aspartate + Inositol + Taurine", notificationRef: "S.O.3295(E)", notificationDate: "2024-08-12" },
  { sn: 12, rawText: "Silymarin + Thiamine Mononitrate + Riboflavin + Pyridoxine HCl + Niacinamide + Calcium pantothenate + Vitamin B12", notificationRef: "S.O.3296(E)", notificationDate: "2024-08-12" },
  { sn: 13, rawText: "Silymarin + Pyridoxine HCl + Cyanocobalamin + Niacinamide + Folic Acid", notificationRef: "S.O.3297(E)", notificationDate: "2024-08-12" },
  { sn: 14, rawText: "Silymarin + Vitamin B6 + Vitamin B12 + Niacinamide + Folic acid + Tricholine Citrate", notificationRef: "S.O.3298(E)", notificationDate: "2024-08-12" },
  { sn: 15, rawText: "Sodium Citrate + Citric Acid Monohydrate Flavored with Cardamom Oil, Caraway Oil, Cinnamon Oil, Clove Oil, Ginger Oil + Alcohol", notificationRef: "S.O.3299(E)", notificationDate: "2024-08-12" },
  { sn: 16, rawText: "Sucralfate + Aceclofenac", notificationRef: "S.O.3300(E)", notificationDate: "2024-08-12" },
  { sn: 17, rawText: "Sucralfate + Domperidone + Dimethicone", notificationRef: "S.O.3301(E)", notificationDate: "2024-08-12" },
  { sn: 18, rawText: "Sucralfate + Domperidone", notificationRef: "S.O.3302(E)", notificationDate: "2024-08-12" },
  { sn: 19, rawText: "Tincture Ipecacuanha + Tincture Urgenia + Camphorated Opium Tincture + Aromatic Spirit of Ammonia + Chloroform + Alcohol", notificationRef: "S.O.3303(E)", notificationDate: "2024-08-12" },
  { sn: 20, rawText: "Ursodeoxycholic Acid + Metformin HCl", notificationRef: "S.O.3304(E)", notificationDate: "2024-08-12" },
  { sn: 21, rawText: "Weak Ginger tincture + Aromatic Spirit of Ammonia + Peppermint Spirit + Chloroform + Sodium Bicarbonate + Compound Cardamom + Alcohol", notificationRef: "S.O.3305(E)", notificationDate: "2024-08-12" },
  { sn: 22, rawText: "Sucralfate + Pantoprazole Sodium + Zinc Gluconate + Light Magnesium Carbonate", notificationRef: "S.O.3306(E)", notificationDate: "2024-08-12" },
  { sn: 23, rawText: "Aloe + Vitamin E Soap", notificationRef: "S.O.3307(E)", notificationDate: "2024-08-12" },
  { sn: 24, rawText: "Povidone Iodine + Metronidazole + Aloe", notificationRef: "S.O.3308(E)", notificationDate: "2024-08-12" },
  { sn: 25, rawText: "Azelaic acid + Tea Tree Oil + Salicylic acid + Allantoin + Zinc oxide + Aloe vera + Jojoba oil + Vitamin E + Soap noodles", notificationRef: "S.O.3309(E)", notificationDate: "2024-08-12" },
  { sn: 26, rawText: "Azithromycin + Adapalene", notificationRef: "S.O.3310(E)", notificationDate: "2024-08-12" },
  { sn: 27, rawText: "Calamine + Aloes + Allantoin", notificationRef: "S.O.3311(E)", notificationDate: "2024-08-12" },
  { sn: 28, rawText: "Calamine + Diphenhydramine Hydrochloride + Aloe + Glycerine + Camphor", notificationRef: "S.O.3312(E)", notificationDate: "2024-08-12" },
  { sn: 29, rawText: "Chlorphenesin + Zinc oxide + Starch", notificationRef: "S.O.3313(E)", notificationDate: "2024-08-12" },
  { sn: 30, rawText: "Clindamycin Phosphate + Zinc acetate", notificationRef: "S.O.3314(E)", notificationDate: "2024-08-12" },
  { sn: 31, rawText: "Gamma Benzene Hexachloride + Benzocaine", notificationRef: "S.O.3315(E)", notificationDate: "2024-08-12" },
  { sn: 32, rawText: "Glucosamine hydrochloride + Diacerein + Menthol + Camphor + Capsaicin", notificationRef: "S.O.3316(E)", notificationDate: "2024-08-12" },
  { sn: 33, rawText: "Hydroxyquinone 2.0%w/w + Octyl Methoxycinnamate 5.0%w/w + Oxybenzone 30%w/w", notificationRef: "S.O.3317(E)", notificationDate: "2024-08-12" },
  { sn: 34, rawText: "Ketoconazole + Zinc Pyrithione + D-Panthenol + Tea Tree Oil + Aloes", notificationRef: "S.O.3318(E)", notificationDate: "2024-08-12" },
  { sn: 35, rawText: "Ketoconazole + Aloe vera + Vitamin A Acetate", notificationRef: "S.O.3319(E)", notificationDate: "2024-08-12" },
  { sn: 36, rawText: "Ketoconazole + Aloes + ZPTO", notificationRef: "S.O.3320(E)", notificationDate: "2024-08-12" },
  { sn: 37, rawText: "Kojic Acid + Arbutin + Octinoxate + Vitamin E + Mulberry", notificationRef: "S.O.3321(E)", notificationDate: "2024-08-12" },
  { sn: 38, rawText: "Lornoxicam + Capsaicin + Menthol + Camphor", notificationRef: "S.O.3322(E)", notificationDate: "2024-08-12" },
  { sn: 39, rawText: "Lornoxicam + Thiocolchicoside + Oleum Lini + Menthol + Methyl salicylate", notificationRef: "S.O.3323(E)", notificationDate: "2024-08-12" },
  { sn: 40, rawText: "Menthol + Aloe vera Topical Spray", notificationRef: "S.O.3324(E)", notificationDate: "2024-08-12" },
  { sn: 41, rawText: "Menthol + Lignocaine HCl + Aloe vera gel + Clotrimazole + Diphenhydramine", notificationRef: "S.O.3325(E)", notificationDate: "2024-08-12" },
  { sn: 42, rawText: "Miconazole nitrate + Gentamicin + Fluocinolone Acetonide + Zinc Sulphate", notificationRef: "S.O.3326(E)", notificationDate: "2024-08-12" },
  { sn: 43, rawText: "Miconazole + Tinidazole", notificationRef: "S.O.3327(E)", notificationDate: "2024-08-12" },
  { sn: 44, rawText: "Minoxidil + Aminexil + Alcohol", notificationRef: "S.O.3328(E)", notificationDate: "2024-08-12" },
  { sn: 45, rawText: "Minoxidil + Azelaic acid + Saw palmetto", notificationRef: "S.O.3329(E)", notificationDate: "2024-08-12" },
  { sn: 46, rawText: "Minoxidil + Aminexil", notificationRef: "S.O.3330(E)", notificationDate: "2024-08-12" },
  { sn: 47, rawText: "Pine Bark extract + Kojic acid + Sodium Ascorbyl Phosphate", notificationRef: "S.O.3331(E)", notificationDate: "2024-08-12" },
  { sn: 48, rawText: "Povidone Iodine + Tinidazole + Zinc sulphate", notificationRef: "S.O.3332(E)", notificationDate: "2024-08-12" },
  { sn: 49, rawText: "Povidone Iodine + Ornidazole + Dexpanthenol", notificationRef: "S.O.3333(E)", notificationDate: "2024-08-12" },
  { sn: 50, rawText: "Salicylic acid + Aloe vera + Allantoin + D-Panthenol", notificationRef: "S.O.3334(E)", notificationDate: "2024-08-12" },
  { sn: 51, rawText: "Silver sulphadiazine + Chlorhexidine Gluconate solution + Allantoin + Aloe vera gel + Vitamin E acetate", notificationRef: "S.O.3335(E)", notificationDate: "2024-08-12" },
  { sn: 52, rawText: "Sodium salicylate + Zinc gluconate + Pyridoxine HCl", notificationRef: "S.O.3336(E)", notificationDate: "2024-08-12" },
  { sn: 53, rawText: "Tetracycline + Colistin Sulphate", notificationRef: "S.O.3337(E)", notificationDate: "2024-08-12" },
  { sn: 54, rawText: "Clomiphene + Ubidecarenone", notificationRef: "S.O.3338(E)", notificationDate: "2024-08-12" },
  { sn: 55, rawText: "Clomiphene Citrate + Estradiol Valerate", notificationRef: "S.O.3339(E)", notificationDate: "2024-08-12" },
  { sn: 56, rawText: "Flavoxate HCl + Ofloxacin", notificationRef: "S.O.3340(E)", notificationDate: "2024-08-12" },
  { sn: 57, rawText: "Clomiphene Citrate + N-Acetylcysteine", notificationRef: "S.O.3341(E)", notificationDate: "2024-08-12" },
  { sn: 58, rawText: "Primerose Oil + Cod liver oil", notificationRef: "S.O.3342(E)", notificationDate: "2024-08-12" },
  { sn: 59, rawText: "Sildenafil Citrate + Papaverine + L-Arginine", notificationRef: "S.O.3343(E)", notificationDate: "2024-08-12" },
  { sn: 60, rawText: "Tranexamic acid + Mefenamic acid + Vitamin K1", notificationRef: "S.O.3344(E)", notificationDate: "2024-08-12" },
  { sn: 61, rawText: "Divalproex Sodium + Oxcarbazepine", notificationRef: "S.O.3345(E)", notificationDate: "2024-08-12" },
  { sn: 62, rawText: "Divalproex Sodium + Levetiracetam", notificationRef: "S.O.3346(E)", notificationDate: "2024-08-12" },
  { sn: 63, rawText: "Ergotamine tartrate + Caffeine + Paracetamol + Prochlorperazine maleate", notificationRef: "S.O.3347(E)", notificationDate: "2024-08-12" },
  { sn: 64, rawText: "Piracetam + Ginkgo biloba extracts + Vinpocetine", notificationRef: "S.O.3348(E)", notificationDate: "2024-08-12" },
  { sn: 65, rawText: "Ginkgo biloba + Methylcobalamin", notificationRef: "S.O.3349(E)", notificationDate: "2024-08-12" },
  { sn: 66, rawText: "Ginkgo biloba + Methylcobalamin + Alpha lipoic acid + Pyridoxine HCl", notificationRef: "S.O.3350(E)", notificationDate: "2024-08-12" },
  { sn: 67, rawText: "Ginseng Extract + Dried extract of Ginkgo Biloba", notificationRef: "S.O.3351(E)", notificationDate: "2024-08-12" },
  { sn: 68, rawText: "Meclizine HCl + Paracetamol + Caffeine", notificationRef: "S.O.3352(E)", notificationDate: "2024-08-12" },
  { sn: 69, rawText: "Nicergoline + Vinpocetine", notificationRef: "S.O.3353(E)", notificationDate: "2024-08-12" },
  { sn: 70, rawText: "Gamma Linolenic Acid + Methylcobalamin", notificationRef: "S.O.3354(E)", notificationDate: "2024-08-12" },
  { sn: 71, rawText: "Beclomethasone Dipropionate + Neomycin Sulphate + Clotrimazole + Lignocaine HCl", notificationRef: "S.O.3355(E)", notificationDate: "2024-08-12" },
  { sn: 72, rawText: "Boric acid + Phenylephrine HCl + Naphazoline Nitrate + Menthol + Camphor", notificationRef: "S.O.3356(E)", notificationDate: "2024-08-12" },
  { sn: 73, rawText: "Naphazoline HCl + Chlorpheniramine Maleate + Zinc Sulphate + Hydroxy Propyl Methyl Cellulose", notificationRef: "S.O.3357(E)", notificationDate: "2024-08-12" },
  { sn: 74, rawText: "Chlorpheniramine Maleate + Naphazoline HCl + Zinc Sulphate + Sodium Chloride + Hydroxy Propyl Methyl Cellulose", notificationRef: "S.O.3358(E)", notificationDate: "2024-08-12" },
  { sn: 75, rawText: "Chlorpheniramine Maleate + Naphazoline HCl + Hydroxy Propyl Methyl Cellulose", notificationRef: "S.O.3359(E)", notificationDate: "2024-08-12" },
  { sn: 76, rawText: "Chlorpheniramine Maleate + Sodium Chloride + Boric Acid + Tetrahydrozoline HCl", notificationRef: "S.O.3360(E)", notificationDate: "2024-08-12" },
  { sn: 77, rawText: "Chlorpheniramine Maleate + Phenylephrine HCl + Antipyrine", notificationRef: "S.O.3361(E)", notificationDate: "2024-08-12" },
  { sn: 78, rawText: "Ketorolac Tromethamine + Chlorpheniramine Maleate + Phenylephrine HCl + Hydroxy Propyl Methyl Cellulose", notificationRef: "S.O.3362(E)", notificationDate: "2024-08-12" },
  { sn: 79, rawText: "Ketorolac Tromethamine + Flurometholone", notificationRef: "S.O.3363(E)", notificationDate: "2024-08-12" },
  { sn: 80, rawText: "Naphazoline HCl + Zinc Sulphate + Boric Acid + Sodium Chloride + Chlorpheniramine Maleate", notificationRef: "S.O.3364(E)", notificationDate: "2024-08-12" },
  { sn: 81, rawText: "Naphazoline HCl + Hydroxy Propyl Methyl Cellulose + Boric Acid + Borax + Menthol + Camphor", notificationRef: "S.O.3365(E)", notificationDate: "2024-08-12" },
  { sn: 82, rawText: "Naphazoline HCl + Hydroxy Propyl Methyl Cellulose + Chlorpheniramine Maleate + Boric Acid + Sodium Chloride + Zinc Sulphate", notificationRef: "S.O.3366(E)", notificationDate: "2024-08-12" },
  { sn: 83, rawText: "Naphazoline HCl + Hydroxy Propyl Methyl Cellulose + Chlorpheniramine Maleate + Boric Acid", notificationRef: "S.O.3367(E)", notificationDate: "2024-08-12" },
  { sn: 84, rawText: "Naphazoline HCl + Chlorpheniramine Maleate + Methyl Cellulose", notificationRef: "S.O.3368(E)", notificationDate: "2024-08-12" },
  { sn: 85, rawText: "Naphazoline HCl + Hydroxy Methyl Cellulose + Boric Acid + Menthol + Camphor", notificationRef: "S.O.3369(E)", notificationDate: "2024-08-12" },
  { sn: 86, rawText: "Naphazoline HCl + Boric Acid + Menthol + Camphor + Methyl Cellulose + Chlorpheniramine Maleate + Zinc Sulphate + Sodium Chloride", notificationRef: "S.O.3370(E)", notificationDate: "2024-08-12" },
  { sn: 87, rawText: "Naphazoline HCl + Phenylephrine HCl + HPMC + Chlorpheniramine Maleate + Menthol + Camphor", notificationRef: "S.O.3371(E)", notificationDate: "2024-08-12" },
  { sn: 88, rawText: "Naphazoline HCl + Hydroxy Propyl Methyl Cellulose + Chlorpheniramine Maleate + Boric Acid + Sodium Chloride + Zinc Sulphate + Menthol + Camphor", notificationRef: "S.O.3372(E)", notificationDate: "2024-08-12" },
  { sn: 89, rawText: "Naphazoline HCl + Hydroxy Propyl Methyl Cellulose + Chlorpheniramine Maleate + Boric Acid + Zinc Sulphate", notificationRef: "S.O.3373(E)", notificationDate: "2024-08-12" },
  { sn: 90, rawText: "Naphazoline HCl + Azelastine HCl + Sodium Carboxy Methyl Cellulose + Menthol + Camphor + Stabilized Oxychlorocomplex", notificationRef: "S.O.3374(E)", notificationDate: "2024-08-12" },
  { sn: 91, rawText: "Naphazoline HCl + Sodium Carboxy Methyl Cellulose + Menthol + Camphor + Stabilized Oxychlorocomplex", notificationRef: "S.O.3375(E)", notificationDate: "2024-08-12" },
  { sn: 92, rawText: "Naphazoline Nitrate + Chlorpheniramine Maleate + Phenylephrine HCl + Hydroxy Methyl Cellulose + Boric Acid + Menthol + Camphor", notificationRef: "S.O.3376(E)", notificationDate: "2024-08-12" },
  { sn: 93, rawText: "Naphazoline Nitrate + Chlorpheniramine Maleate + Zinc Sulphate + Boric Acid + Sodium Chloride", notificationRef: "S.O.3377(E)", notificationDate: "2024-08-12" },
  { sn: 94, rawText: "Norfloxacin + Tinidazole (with Betacyclodextrin) Eye ointment", notificationRef: "S.O.3378(E)", notificationDate: "2024-08-12" },
  { sn: 95, rawText: "Ofloxacin + Beclomethasone Dipropionate + Lignocaine HCl", notificationRef: "S.O.3379(E)", notificationDate: "2024-08-12" },
  { sn: 96, rawText: "Naphazoline HCl + Chlorpheniramine Maleate + Phenylephrine HCl + Menthol + Camphor", notificationRef: "S.O.3380(E)", notificationDate: "2024-08-12" },
  { sn: 97, rawText: "Phenylephrine HCl + Naphazoline HCl + Menthol + Camphor + Hydroxy Propyl Methyl Cellulose", notificationRef: "S.O.3381(E)", notificationDate: "2024-08-12" },
  { sn: 98, rawText: "Phenylephrine HCl + Naphazoline HCl + Menthol + Camphor", notificationRef: "S.O.3382(E)", notificationDate: "2024-08-12" },
  { sn: 99, rawText: "Sulphacetamide Sodium + Zinc Sulphate + Chlorpheniramine Maleate + Boric acid + Sodium Chloride", notificationRef: "S.O.3383(E)", notificationDate: "2024-08-12" },
  { sn: 100, rawText: "Zinc Sulphate + Boric acid + Naphazoline HCl + Sodium Chloride + Phenyl Ethyl Alcohol", notificationRef: "S.O.3384(E)", notificationDate: "2024-08-12" },
  { sn: 101, rawText: "Cetirizine HCl + Paracetamol + Phenylephrine HCl", notificationRef: "S.O.3385(E)", notificationDate: "2024-08-12" },
  { sn: 102, rawText: "Cetirizine HCl + Phenylephrine HCl", notificationRef: "S.O.3386(E)", notificationDate: "2024-08-12" },
  { sn: 103, rawText: "Levocetirizine + Phenylephrine HCl", notificationRef: "S.O.3387(E)", notificationDate: "2024-08-12" },
  { sn: 104, rawText: "Levocetirizine + Phenylephrine HCl + Paracetamol", notificationRef: "S.O.3388(E)", notificationDate: "2024-08-12" },
  { sn: 105, rawText: "Phenylephrine HCl + Paracetamol + Levocetirizine HCl + Menthol", notificationRef: "S.O.3389(E)", notificationDate: "2024-08-12" },
  { sn: 106, rawText: "Levocetirizine HCl + Ambroxol HCl + Paracetamol", notificationRef: "S.O.3390(E)", notificationDate: "2024-08-12" },
  { sn: 107, rawText: "Levocetirizine HCl + Ambroxol HCl + Phenylephrine HCl", notificationRef: "S.O.3391(E)", notificationDate: "2024-08-12" },
  { sn: 108, rawText: "Diethylcarbamazine Citrate + Chlorpheniramine maleate", notificationRef: "S.O.3392(E)", notificationDate: "2024-08-12" },
  { sn: 109, rawText: "Diethylcarbamazine Citrate + Levocetirizine HCl", notificationRef: "S.O.3393(E)", notificationDate: "2024-08-12" },
  { sn: 110, rawText: "Ambroxol HCl + Phenylephrine HCl + Guaiphenesin", notificationRef: "S.O.3394(E)", notificationDate: "2024-08-12" },
  { sn: 111, rawText: "Bromhexine HCl + Phenylephrine HCl", notificationRef: "S.O.3395(E)", notificationDate: "2024-08-12" },
  { sn: 112, rawText: "Etofylline + Theophylline anhydrous eq. to Theophylline hydrate + Ambroxol HCl", notificationRef: "S.O.3396(E)", notificationDate: "2024-08-12" },
  { sn: 113, rawText: "Etofylline + Theophylline anhydrous eq. to Theophylline hydrate + Montelukast", notificationRef: "S.O.3397(E)", notificationDate: "2024-08-12" },
  { sn: 114, rawText: "Ambroxol HCl + Terbutaline Sulphate + Ammonium Chloride + Guaiphenesin + Menthol", notificationRef: "S.O.3398(E)", notificationDate: "2024-08-12" },
  { sn: 115, rawText: "Ambroxol HCl + Salbutamol Sulphate + Ammonium Chloride + Guaiphenesin + Menthol", notificationRef: "S.O.3399(E)", notificationDate: "2024-08-12" },
  { sn: 116, rawText: "Cetirizine HCl + Terbutaline Sulphate + Ambroxol HCl + Guaiphenesin", notificationRef: "S.O.3400(E)", notificationDate: "2024-08-12" },
  { sn: 117, rawText: "Dextromethorphan Hydrobromide + Chlorpheniramine Maleate + Ammonium Chloride + Sodium Citrate + Menthol", notificationRef: "S.O.3401(E)", notificationDate: "2024-08-12" },
  { sn: 118, rawText: "Salbutamol Sulphate + Bromhexine HCl + Guaiphenesin + Ammonium Chloride + Menthol", notificationRef: "S.O.3402(E)", notificationDate: "2024-08-12" },
  { sn: 119, rawText: "Terbutaline Sulphate + Bromhexine HCl + Chlorpheniramine Maleate", notificationRef: "S.O.3403(E)", notificationDate: "2024-08-12" },
  { sn: 120, rawText: "Chlorpheniramine Maleate + P.G Sulphonate + Ammonium Chloride + Sodium Citrate + Menthol", notificationRef: "S.O.3404(E)", notificationDate: "2024-08-12" },
  { sn: 121, rawText: "Aminophylline + Ammonium Chloride + Sodium Citrate", notificationRef: "S.O.3405(E)", notificationDate: "2024-08-12" },
  { sn: 122, rawText: "Paracetamol + Chlorpheniramine Maleate + Phenyl Propanolamine", notificationRef: "S.O.3406(E)", notificationDate: "2024-08-12" },
  { sn: 123, rawText: "Trithioparamethoxyphenyl Propene + Chlorpheniramine Maleate", notificationRef: "S.O.3407(E)", notificationDate: "2024-08-12" },
  { sn: 124, rawText: "Aceclofenac 50mg + Paracetamol 125mg oral liquid", notificationRef: "S.O.3408(E)", notificationDate: "2024-08-12" },
  { sn: 125, rawText: "Aceclofenac 50mg + Paracetamol 125mg tablet", notificationRef: "S.O.3409(E)", notificationDate: "2024-08-12" },
  { sn: 126, rawText: "Adenosine triphosphate diphosphate + Magnesium Orotate", notificationRef: "S.O.3410(E)", notificationDate: "2024-08-12" },
  { sn: 127, rawText: "Amoxicillin Trihydrate + Dicloxacillin Sodium + Lactobacillus", notificationRef: "S.O.3411(E)", notificationDate: "2024-08-12" },
  { sn: 128, rawText: "Camylofin Dihydrochloride 25mg + Paracetamol 300mg", notificationRef: "S.O.3412(E)", notificationDate: "2024-08-12" },
  { sn: 129, rawText: "Cefixime + Acetyl Cysteine", notificationRef: "S.O.3413(E)", notificationDate: "2024-08-12" },
  { sn: 130, rawText: "Cephalexin Monohydrate + Serratiopeptidase", notificationRef: "S.O.3414(E)", notificationDate: "2024-08-12" },
  { sn: 131, rawText: "Cetyl Myristoleate + Glucosamine Sulphate Potassium + Methyl Sulfonyl methane", notificationRef: "S.O.3415(E)", notificationDate: "2024-08-12" },
  { sn: 132, rawText: "Diacerein IP + Glucosamine Sulphate Potassium Chloride USP + MSM (Methylsulphonyl Methane) + Cetyl Myristoleate", notificationRef: "S.O.3416(E)", notificationDate: "2024-08-12" },
  { sn: 133, rawText: "Paracetamol + Diclofenac Potassium + Caffeine Anhydrous", notificationRef: "S.O.3417(E)", notificationDate: "2024-08-12" },
  { sn: 134, rawText: "Diclofenac sodium + Thiocolchicoside Injection", notificationRef: "S.O.3418(E)", notificationDate: "2024-08-12" },
  { sn: 135, rawText: "Doxycycline + Ornidazole + Bromelain + Lactobacillus Rhamnosus + Lactobacillus Reuteri RC", notificationRef: "S.O.3419(E)", notificationDate: "2024-08-12" },
  { sn: 136, rawText: "Doxycycline HCl + Betacyclodextrin + Serratiopeptidase", notificationRef: "S.O.3420(E)", notificationDate: "2024-08-12" },
  { sn: 137, rawText: "Erythromycin stearate eq. to Erythromycin + Lactic acid Bacillus", notificationRef: "S.O.3421(E)", notificationDate: "2024-08-12" },
  { sn: 138, rawText: "Etodolac + Paracetamol + Serratiopeptidase", notificationRef: "S.O.3422(E)", notificationDate: "2024-08-12" },
  { sn: 139, rawText: "Flupirtine Maleate 400mg + Paracetamol 325mg tablet", notificationRef: "S.O.3423(E)", notificationDate: "2024-08-12" },
  { sn: 140, rawText: "Glucosamine sulphate potassium chloride 410mg + Chondroitin Sulphate 100mg", notificationRef: "S.O.3424(E)", notificationDate: "2024-08-12" },
  { sn: 141, rawText: "Glucosamine sulphate potassium chloride + Methyl Sulphonyl Methane (MSM) + Sodium Borate + Copper Sulphate pentahydrate + Manganese Sulphate + Vitamin D3", notificationRef: "S.O.3425(E)", notificationDate: "2024-08-12" },
  { sn: 142, rawText: "Glucosamine Sulphate + Sodium chloride + Manganese + Boron + Zinc + Copper", notificationRef: "S.O.3426(E)", notificationDate: "2024-08-12" },
  { sn: 143, rawText: "Glucosamine sulphate + Chondroitin sulphate + Methylsulfonylmethane + Vitamin D3 + Vitamin E + Vitamin C + Selenium + Elemental Zinc + Elemental Manganese + Elemental Chromium + Elemental Copper + Elemental Boron", notificationRef: "S.O.3427(E)", notificationDate: "2024-08-12" },
  { sn: 144, rawText: "Glucosamine sulphate + Methyl sulfonyl methane + Manganese sulphate + Vitamin E acetate + Calcium Carbonate", notificationRef: "S.O.3428(E)", notificationDate: "2024-08-12" },
  { sn: 145, rawText: "Glucosamine Sulphate + Vitamin E acetate + Calcium Pantothenate + Vitamin D3", notificationRef: "S.O.3429(E)", notificationDate: "2024-08-12" },
  { sn: 146, rawText: "Glucosamine Sulphate Potassium chloride + Calcium Carbonate from an organic source (oyster shell) eq. to elemental Calcium + Vitamin D3", notificationRef: "S.O.3430(E)", notificationDate: "2024-08-12" },
  { sn: 147, rawText: "Cetyl Myristoleate + Glucosamine Sulphate Potassium chloride + Methyl sulfonyl methane", notificationRef: "S.O.3431(E)", notificationDate: "2024-08-12" },
  { sn: 148, rawText: "Glucosamine Sulphate Potassium chloride + Methyl sulfonyl methane + Calcium carbonate + Vitamin E + Manganese", notificationRef: "S.O.3432(E)", notificationDate: "2024-08-12" },
  { sn: 149, rawText: "Glucosamine Sulphate Potassium chloride + Calcium carbonate + Methyl sulfonyl methane + Vitamin D3", notificationRef: "S.O.3433(E)", notificationDate: "2024-08-12" },
  { sn: 150, rawText: "Glucosamine Sulphate Potassium + Methyl sulphate Sodium + Sulphonyl Methane + Chondroitin Sulphate Sodium + Calcium Carbonate + Vitamin D3 + Sodium Borate + Cupric Oxide + Colloidal Silicon Dioxide + Manganese Chloride", notificationRef: "S.O.3434(E)", notificationDate: "2024-08-12" },
  { sn: 151, rawText: "Methocarbamol + Diclofenac Sodium Injection", notificationRef: "S.O.3435(E)", notificationDate: "2024-08-12" },
  { sn: 152, rawText: "Paracetamol + Pentazocine", notificationRef: "S.O.3436(E)", notificationDate: "2024-08-12" },
  { sn: 153, rawText: "Sucralfate + Domperidone + Simethicone", notificationRef: "S.O.3437(E)", notificationDate: "2024-08-12" },
  { sn: 154, rawText: "Sulfaquinoxaline + Diaveridine HCl + Vitamin K", notificationRef: "S.O.3438(E)", notificationDate: "2024-08-12" },
  { sn: 155, rawText: "Tramadol HCl + Dicyclomine HCl + Domperidone", notificationRef: "S.O.3439(E)", notificationDate: "2024-08-12" },
  { sn: 156, rawText: "Tramadol HCl + Paracetamol + Caffeine + Taurine", notificationRef: "S.O.3440(E)", notificationDate: "2024-08-12" },
];
